# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_æ•´ç‚¹çº¢åŒ…é›¨ğŸ§§

on:
  workflow_dispatch:
  schedule:
    - cron: '0,20 * * * *'

jobs:
  build:
    env:
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
#      SCKEY: ${{ secrets.PUSH_KEY }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          ${{ secrets.JD_HTTPS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # ä½¿ç”¨ GitHub å®˜æ–¹çš„ç¼“å­˜ Actionã€‚
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ä½¿ç”¨ package-lock.json çš„ Hash ä½œä¸ºç¼“å­˜çš„ keyã€‚ä¹Ÿå¯ä»¥ä½¿ç”¨ package.json ä»£æ›¿
      - name: npm install
        run: |
          cd ~/TaskAction
          git checkout master
          npm install

      - name: 'è¿è¡Œ ã€æ•´ç‚¹çº¢åŒ…é›¨ğŸ§§ã€‘'
        run: |
          cd ~/TaskAction
          node jd_super_redrain.js






