# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东循环任务

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    env:
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          ${{ secrets.JD_HTTPS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/TaskAction
          git checkout master
          npm install

#      - name: '运行 【京东种豆得豆】'
#        run: |
#          cd ~/TaskAction
#          node jd_plantBean.js
#        env:
#          PLANT_BEAN_SHARECODES: ${{ secrets.PLANT_BEAN_SHARECODES }}
          

#      - name: '运行 【东东农场】'
#        run: |
#          cd ~/TaskAction
#          node jd_fruit.js
#        env:
#          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
          
#      - name: '运行 【东东工厂】'
#        run: |
#          cd ~/TaskAction
#          node jd_jdfactory.js
#        env:
#          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}


#      - name: '运行 【京喜农场】'
#        run: |
#          cd ~/TaskAction
#          node jd_jxnc.js
#        env:
#          JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
#          JXNC_SHARECODES: ${{ secrets.JXNC_SHARECODES }}


#      - name: '运行 【京喜工厂】'
#        run: |
#          cd ~/TaskAction
#          node jd_dreamFactory.js
#        env:
#          JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
#          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }}


#      - name: '运行 【东东萌宠】'
#        run: |
#          cd ~/TaskAction
#          node jd_pet.js
#        env:
#          PETSHARECODES: ${{ secrets.PETSHARECODES }}


#      - name: '运行 【东东超市】'
#        run: |
#          cd ~/TaskAction
#          node jd_superMarket.js
#        env:
#          JOIN_PK_TEAM: ${{ secrets.JOIN_PK_TEAM }}
          

      - name: '运行 【口袋书店】'
        run: |
          cd ~/TaskAction
          node jd_bookshop.js



      - name: '运行 【宠汪汪积分兑换奖品】'
        run: |
          cd ~/TaskAction
          node jd_joy_reward.js


      - name: '运行 【宠汪汪偷好友积分与狗】'
        run: |
          cd ~/TaskAction
          node jd_joy_steal.js
        env:
          JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED }}
          JOY_FEED_COUNT: ${{ secrets.JOY_FEED_COUNT }}
          

      - name: '运行 【点点券】'
        run: |
          cd ~/TaskAction
          node jd_necklace.js


      - name: '运行 【京东天天加速】'
        run: |
          cd ~/TaskAction
          node jd_speed.js


      - name: '运行 【天天提鹅】'
        run: |
          cd ~/TaskAction
          node jd_daily_egg.js


      - name: '运行 【crazyJoy任务】'
        run: |
          cd ~/TaskAction
          node jd_crazy_joy.js
        env:
          JDJOY_APPLYJDBEAN: ${{ secrets.JDJOY_APPLYJDBEAN }}
          

      - name: '运行 【京东财富岛】'
        run: |
          cd ~/TaskAction
          node jd_cfd.js


      - name: '运行 【京东摇钱树】'
        run: |
          cd ~/TaskAction
          node jd_moneyTree.js
        env:
          MONEY_TREE_SELL_FRUIT: ${{ secrets.MONEY_TREE_SELL_FRUIT }}


      - name: '运行 【她的节享京豆】'
        run: |
          cd ~/TaskAction
          node jd_firecrackers.js
        env:
          FIRECRACKERS_NOTITY_BEAN: ${{ secrets.FIRECRACKERS_NOTITY_BEAN }}


      - name: '运行 【美丽研究院】'
        run: |
          cd ~/TaskAction
          node jd_beauty.js




