# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 半小时任务

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  build:
    env:
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install



      - name: '运行 【电视家】'
        run: |
          node ./workflow/sunert/dianshijia.js
        env:
          TZ: Asia/shanghai
          DSJ_HEADERS: ${{ secrets.DSJ_HEADERS }}
          DSJ_DRAWAL: ${{ secrets.DSJ_DRAWAL }}


      - name: '运行 【今日头条极速版】'
        run: |
          node ./workflow/jrtt.js
        env:
          TZ: Asia/shanghai


      - name: '运行 【步步宝】'
        run: |
          node ./workflow/bbb/BBB.js
        env:
          TZ: Asia/shanghai


      - name: '运行 【步步宝1】'
        run: |
          node ./workflow/bbb/BBB2.js
        env:
          TZ: Asia/shanghai


      - name: '运行 【抖音火山版】'
        run: |
          node ./workflow/huoshan.js
        env:
          TZ: Asia/shanghai
